// Public brand copy only. No scripture quotations or operational data.
const sectionTitle = (label, title, text) => `<div class="section-heading"><p class="eyebrow">${label}</p><h2>${title}</h2><p>${text}</p></div>`;
const button = (href, text, secondary = false) => `<a class="button${secondary ? ' secondary' : ''}" href="${href}">${text}<span aria-hidden="true">↗</span></a>`;
export const traditions = [['Protestant', '개신교'], ['Catholic', '가톨릭'], ['Buddhism', '불교'], ['Judaism', '유대교'], ['Islam', '이슬람'], ['Hinduism', '힌두교'], ['Confucianism', '유교']];
export const about = () => `<section id="why" class="section split">${sectionTitle('02 / WHY ONARIA', '마음을 이해하는 일은,<br>다름을 존중하는 일.', '같은 하루를 살아도, 마음에 남는 것은 저마다 다릅니다.')}<div class="prose"><p class="lead">ONARIA는 AI와의 안전한 마음대화로 나를 돌아보고,<br>현재의 감정과 상황을 성경 말씀과 작은 실천으로 연결하는 신앙 기반 마음관리 서비스입니다.</p><p>신앙적 답을 서둘러 강요하기보다 마음을 먼저 듣습니다. 기술은 말씀과 공동체로 다시 연결되는 시간을 돕고, 선택과 판단은 언제나 사람에게 남습니다.</p><a class="text-link" href="/about">우리의 생각 <span aria-hidden="true">→</span></a></div></section>`;
const steps = [
  ['Emotion', '마음 선택', '오늘 마음은 어떤가요? 감정과 강도를 고르고, 이름 붙이기 어려운 마음은 직접 적어 보세요.'],
  ['Conversation', '마음대화', '선택한 마음에 맞는 상황 예시를 참고해 이야기를 시작합니다. 다음 질문과 예시는 대화의 맥락에 맞춰 달라집니다.'],
  ['Scripture & action', '말씀과 작은 실천', '마음을 돌아본 뒤 성경 말씀과 오늘 가능한 작은 실천을 만납니다. 원하는 기록은 마음카드로 기기에 저장합니다.'],
];
export const flow = () => `<section id="how-it-works" class="section flow-section">${sectionTitle('03 / HOW IT WORKS', '마음에서 시작하는 세 걸음.', '마음 선택 → 마음대화 → 말씀과 작은 실천. 서두르지 않고 나의 속도로 이어갑니다.')}<ol class="journey">${steps.map(([en, ko, text], i) => `<li><details${i === 0 ? ' open' : ''}><summary><span class="step-number" aria-hidden="true">0${i + 1}</span><span><span class="step-en" lang="en">${en}</span><span class="step-name">${ko}</span></span><span class="step-toggle" aria-hidden="true">+</span></summary><p>${text}</p></details></li>`).join('')}</ol></section>`;
export const services = () => `<section id="conversation" class="section split conversation-section">${sectionTitle('04 / AI CONVERSATION', '말할 수 있는 만큼.<br>당신의 속도로.', 'ONARIA가 지향하는 AI는 마음을 단정하는 답변자가 아니라, 스스로 돌아보도록 질문하는 대화 상대입니다.')}<div class="reflection-panel"><p class="eyebrow">A MOMENT TO REFLECT</p><h3>지금, 어떤 마음인가요?</h3><p>감정에서 시작해 상황과 생각을 돌아보고,<br>오늘 할 수 있는 작은 행동으로 이어집니다.</p><div class="reflection-line" aria-hidden="true"></div><p class="note">현재 개발 앱의 경험을 소개합니다.<br>이 홈페이지에서는 AI 대화를 실행하지 않습니다.</p></div></section>`;
export const seven = () => `<section id="paths" class="section traditions">${sectionTitle('05 / SEVEN PATHS', '일곱 개의 길.<br>동등한 존중.', '어느 전통도 다른 전통의 위에 놓지 않습니다. 출처와 맥락을 지키며, 각자의 언어로 성찰할 수 있는 경험을 준비합니다.')}<div class="tradition-grid">${traditions.map(([en, ko]) => `<article class="tradition-card"><span class="path-light" aria-hidden="true"></span><h3>${ko}</h3><p lang="en">${en}</p><span class="status">준비 중</span></article>`).join('')}</div><p class="note">전통별 서비스의 정식 공개 전입니다. 현재 ONARIA에서는 성경 기반의 흐름을 테스트하며, 이는 일곱 전통 전체의 출시를 의미하지 않습니다.</p></section>`;
export const apps = () => `<section id="apps" class="section app-section"><div>${sectionTitle('06 / ONARIA', '마음에서 시작하는<br>성경 기반의 성찰.', 'ONARIA는 감정 체크인, AI 마음대화, 말씀 연결, 작은 실천과 기록을 하나의 모바일 경험으로 연결합니다.')}<p class="availability">Closed Beta 준비 중<br>Android · iOS 앱 검증 중 · 웹은 서비스 안내</p><p class="note">현재 핵심 기능과 안전성을 검증하고 있습니다.<br>일반 공개 스토어 출시 전이며, 이 웹에서는 로그인이나 마음대화를 실행하지 않습니다.</p></div><div class="mind-card"><span class="eyebrow">ONARIA / EXPERIENCE</span><h3>마음이 머문 자리를<br>한 장에 담다.</h3><ol class="mind-stages">${['Emotion', 'Conversation', 'Scripture', 'Small Action', 'Mind Card'].map((text, i) => `<li><span aria-hidden="true">0${i + 1}</span><span lang="en">${text}</span></li>`).join('')}</ol><p class="note">기능 흐름 소개 · 실제 사용자 기록이 아닙니다</p></div></section>`;
export const safety = () => `<section id="safety" class="section trust-section">${sectionTitle('07 / SAFETY & TRUST', '기술보다 먼저,<br>사람을 생각합니다.', '빠른 답변보다 지켜야 할 원칙이 있습니다.')}<div class="trust-grid">${[
  ['Safety First', '위험한 순간에는 현실의 도움부터', '위기 신호가 있는 경우 외부 AI 호출을 기다리지 않고 안전 안내를 우선합니다. AI 응답을 기다리기보다 현실의 긴급 지원이 필요한 순간이 있습니다.'],
  ['Privacy by Design', '필요한 정보만, 신중하게', '대화 맥락과 사용량은 목적에 맞게 처리합니다. 데이터 처리 범위와 출시 전 확정할 사항을 공개합니다.'],
  ['Source Integrity', '출처가 없으면, 단정하지 않기', '경전과 종교 자료의 맥락을 존중합니다. 충분한 근거가 없는 내용을 권위 있는 인용처럼 제시하지 않습니다.'],
  ['Human-centered AI', '교회와 전문가를 대신하지 않는 AI', 'AI는 목회자·교회 공동체·의료인·심리치료사를 대신하지 않습니다. 마음을 돌아보고 말씀과 공동체, 필요한 경우 전문적인 도움으로 다시 연결되는 첫 디지털 접점을 지향합니다.'],
].map(([en, ko, text]) => `<article><p class="eyebrow" lang="en">${en}</p><h3>${ko}</h3><p>${text}</p></article>`).join('')}</div></section>`;
export const privacy = () => `<section id="privacy" class="section split privacy-section">${sectionTitle('08 / PRIVACY', '개인적인 이야기에는<br>분명한 설명이 필요하니까.', '무엇이 기기에 남고, 무엇이 서버로 전달되는지 알 수 있어야 합니다.')}<div class="prose"><p>마음 카드 등 일부 기록은 기기에 보관됩니다. AI 응답에는 입력한 내용과 필요한 대화 맥락이 서버로 전달되며, 전달 대상과 항목을 확인하고 허용한 경우에만 외부 AI 제공자가 처리할 수 있습니다.</p><p>이 홈페이지에는 광고 추적 도구나 개인정보 수집 폼을 두지 않았습니다. 정식 공개 전 확정해야 할 운영 정보도 안내합니다.</p><a class="text-link" href="/privacy">개인정보 처리 안내 읽기 <span aria-hidden="true">→</span></a></div></section>`;
export const ecosystem = () => `<section id="ecosystem" class="section ecosystem">${sectionTitle('09 / THE ONARIA ECOSYSTEM', '하나의 철학,<br>서로 다른 경험으로.', '마음을 이해하고, 각자의 가치를 존중하는 ONARIA의 방향 아래 서비스 확장을 구상합니다.')}<div class="ecosystem-root"><img src="/assets/onaria-emblem.svg" alt="" width="56" height="56" loading="lazy"><span>ONARIA</span><p>EVERY HEART HAS ITS OWN WAY</p></div><ul class="ecosystem-list">${['ONARIA', 'Catholic', 'Buddhist', 'Jewish', 'Islamic', 'Hindu', 'Confucian'].map((name, i) => `<li><span lang="en">${name}</span><span class="status">${i === 0 ? '개발·테스트 중' : '확장 구상 · 미출시'}</span></li>`).join('')}</ul><p class="note">향후 방향을 나타낸 구조입니다. 서비스명과 출시 일정은 확정되지 않았습니다.</p></section>`;
export const cta = () => `<section class="cta"><img src="/assets/onaria-emblem.svg" width="64" height="64" loading="lazy" alt=""><p class="eyebrow">10 / YOUR WAY, AT YOUR PACE</p><h2>당신의 길은,<br>지금의 마음에서 시작됩니다.</h2>${button('/services', 'ONARIA의 경험 더 알아보기')}</section>`;
export const faq = () => `<section id="account-help" class="section faq-section">${sectionTitle('ACCOUNT & RECORDS', '계정과 기록, 먼저 알아두세요.', '앱의 계정 관리에서 로그인 수단과 개인정보를 관리할 수 있습니다.')}<div class="faq-list">${[
  ['어떤 계정으로 로그인하나요?', '네이버 · Google · 카카오 · Apple 로그인을 지원합니다. 기존 계정에 다른 소셜 계정을 연결할 수 있습니다. 같은 휴대폰 번호만으로 자동 연결하지 않으며, 기존 계정의 본인확인이 필요합니다.'],
  ['회원탈퇴는 어디에서 하나요?', '앱 메뉴의 계정 관리 → 회원탈퇴에서 진행합니다. Apple 계정이 연결돼 있다면 Apple 본인확인이 다시 필요합니다.'],
  ['탈퇴하면 마음카드도 없어지나요?', '회원탈퇴와 기기 기록 삭제는 별개입니다. 마음카드·말씀·여정 등 기기에 저장한 기록은 앱의 기록 삭제 기능에서 따로 관리하세요. 백업과 운영 기록의 처리 범위는 개인정보 처리 안내에서 확인할 수 있습니다.'],
  ['예시문은 제 기록인가요?', '예시문은 마음을 표현하기 위한 안내입니다. 선택한 마음과 질문에 맞게 달라지며, 실제 사용자의 기록을 공개한 것이 아닙니다.'],
  ['어떤 성경을 사용하나요?', '한국어는 성경전서 개역한글판, 영어는 World English Bible(WEB), eBible.org 출처를 표시합니다. 출처와 번역명을 유지하며 근거 없는 인용을 만들지 않습니다.'],
].map(([q,a]) => `<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div><a class="text-link" href="/account-deletion">계정 및 데이터 삭제 안내 →</a></section>`;
export const home = () => `<section class="hero"><div class="hero-copy"><p class="wordmark">ONARIA</p><h1>오늘의 마음을 듣고,<br>작은 실천으로.</h1><p class="hero-english" lang="en">EVERY HEART HAS ITS OWN WAY</p><p class="hero-description">마음 선택 → 마음대화 → 성경 말씀과 작은 실천.<br>기독교 신앙을 바탕으로, 나의 속도로 마음을 돌아보세요.</p><div class="hero-actions">${button('/#how-it-works', '앱 경험 살펴보기')}${button('/#account-help', '계정과 기록 안내', true)}</div><p class="hero-note">Closed Beta 준비 중 · 일반 공개 스토어 출시 전</p></div><div class="hero-art"><div class="preview-label">앱 흐름 소개 · 실제 사용자 기록이 아닙니다</div><div class="app-preview"><img src="/assets/onaria-emblem.svg" width="48" height="48" alt=""><p class="eyebrow">오늘의 마음</p><h2>오늘 마음은<br>어떤가요?</h2><ul class="emotion-preview" aria-label="감정 카드 예시"><li>기쁨</li><li>불안</li><li>감사</li><li>복잡한 마음</li></ul><p>마음을 고르고, 이야기하고,<br>말씀과 작은 실천으로 이어가요.</p><span class="preview-next">마음대화 →</span></div></div><a class="scroll-cue" href="#why">ONARIA 소개 <span aria-hidden="true">↓</span></a></section>${about()}${flow()}${services()}${apps()}${safety()}${privacy()}${faq()}${cta()}`;
