// Public brand copy only. No scripture quotations or operational data.
const sectionTitle = (label, title, text) => `<div class="section-heading"><p class="eyebrow">${label}</p><h2>${title}</h2><p>${text}</p></div>`;
const button = (href, text, secondary = false) => `<a class="button${secondary ? ' secondary' : ''}" href="${href}">${text}<span aria-hidden="true">↗</span></a>`;
export const traditions = [['Protestant', '개신교'], ['Catholic', '가톨릭'], ['Buddhism', '불교'], ['Judaism', '유대교'], ['Islam', '이슬람'], ['Hinduism', '힌두교'], ['Confucianism', '유교']];
export const about = () => `<section id="why" class="section split">${sectionTitle('02 / WHY ONARIA', '마음을 이해하는 일은,<br>다름을 존중하는 일.', '같은 하루를 살아도, 마음에 남는 것은 저마다 다릅니다.')}<div class="prose"><p class="lead">ONARIA는 AI와의 안전한 마음대화로 나를 돌아보고,<br>현재의 감정과 상황을 성경 말씀과 작은 실천으로 연결하는 신앙 기반 마음관리 서비스입니다.</p><p>신앙적 답을 서둘러 강요하기보다 마음을 먼저 듣습니다. 기술은 말씀과 공동체로 다시 연결되는 시간을 돕고, 선택과 판단은 언제나 사람에게 남습니다.</p><a class="text-link" href="/about">우리의 생각 <span aria-hidden="true">→</span></a></div></section>`;
const steps = [
  ['Emotion', '마음 선택', '오늘 느끼는 감정과 강도를 고릅니다. 이름 붙이기 어려운 마음은 직접 적을 수도 있습니다.'],
  ['Conversation', 'AI와 짧은 대화', '글이나 음성으로 마음을 표현합니다. 짧은 질문을 따라 나의 이야기를 꺼내 봅니다.'],
  ['Understanding', '현재 마음 이해', '어떤 상황과 생각이 마음에 남았는지 돌아봅니다. AI가 나를 진단하는 과정은 아닙니다.'],
  ['Scripture', '말씀 연결', '현재의 감정과 상황을 돌아본 뒤 관련 성경 말씀과 신앙적 성찰로 연결합니다. 말씀을 감정을 억누르는 정답처럼 사용하지 않습니다.'],
  ['Small action', '작은 행동', '오늘 해볼 수 있는 작은 실천을 고릅니다. 대단한 변화보다 가능한 한 걸음을 생각합니다.'],
  ['Mind card', '마음 카드', '대화에서 발견한 마음과 실천을 카드로 정리하고 기기에 저장해 돌아봅니다.'],
];
export const flow = () => `<section id="how-it-works" class="section flow-section">${sectionTitle('03 / HOW IT WORKS', '큰 답보다, 작은 발견 여섯 번.', '각 단계를 열어 현재 앱의 경험을 살펴보세요. 원하는 만큼 머물러도 괜찮습니다.')}<ol class="journey">${steps.map(([en, ko, text], i) => `<li><details${i === 0 ? ' open' : ''}><summary><span class="step-number" aria-hidden="true">0${i + 1}</span><span><span class="step-en" lang="en">${en}</span><span class="step-name">${ko}</span></span><span class="step-toggle" aria-hidden="true">+</span></summary><p>${text}</p></details></li>`).join('')}</ol></section>`;
export const services = () => `<section id="conversation" class="section split conversation-section">${sectionTitle('04 / AI CONVERSATION', '말할 수 있는 만큼.<br>당신의 속도로.', 'ONARIA가 지향하는 AI는 마음을 단정하는 답변자가 아니라, 스스로 돌아보도록 질문하는 대화 상대입니다.')}<div class="reflection-panel"><p class="eyebrow">A MOMENT TO REFLECT</p><h3>지금, 어떤 마음인가요?</h3><p>감정에서 시작해 상황과 생각을 돌아보고,<br>오늘 할 수 있는 작은 행동으로 이어집니다.</p><div class="reflection-line" aria-hidden="true"></div><p class="note">현재 개발 앱의 경험을 소개합니다.<br>이 홈페이지에서는 AI 대화를 실행하지 않습니다.</p></div></section>`;
export const seven = () => `<section id="paths" class="section traditions">${sectionTitle('05 / SEVEN PATHS', '일곱 개의 길.<br>동등한 존중.', '어느 전통도 다른 전통의 위에 놓지 않습니다. 출처와 맥락을 지키며, 각자의 언어로 성찰할 수 있는 경험을 준비합니다.')}<div class="tradition-grid">${traditions.map(([en, ko]) => `<article class="tradition-card"><span class="path-light" aria-hidden="true"></span><h3>${ko}</h3><p lang="en">${en}</p><span class="status">준비 중</span></article>`).join('')}</div><p class="note">전통별 서비스의 정식 공개 전입니다. 현재 ONARIA에서는 성경 기반의 흐름을 테스트하며, 이는 일곱 전통 전체의 출시를 의미하지 않습니다.</p></section>`;
const platformIcon = name => {
  const paths = {
    android: '<path d="m7 7-2-3m12 3 2-3M4 14a8 8 0 0 1 16 0v4H4Z"/><circle cx="8" cy="12" r=".8" fill="currentColor" stroke="none"/><circle cx="16" cy="12" r=".8" fill="currentColor" stroke="none"/>',
    ios: '<path fill="currentColor" stroke="none" d="M16.4 2c.2 1.5-.5 3-1.4 4-.9 1-2.3 1.6-3.6 1.5-.2-1.4.5-2.9 1.4-3.9.9-.9 2.5-1.6 3.6-1.6ZM19.5 15.5c-.5 1.1-.7 1.6-1.3 2.6-.9 1.4-2.1 3.2-3.7 3.2-1.4 0-1.8-.9-3.7-.9-1.8 0-2.3.9-3.7.9-1.5 0-2.7-1.6-3.6-3C1 14.4 1.7 8.8 5.6 8c1.6-.4 2.9.6 4 .6 1 0 2.7-1.1 4.6-.8 1.6.2 2.8.9 3.6 2-3.2 1.8-2.7 6 .7 7.2Z"/>',
    web: '<rect x="3" y="4" width="18" height="16" rx="3"/><path d="M3 9h18M7 6.5h.01M10 6.5h.01m-1 7 3 2-3 2m5 0h3"/>',
  };
  return `<svg class="platform-icon" viewBox="0 0 24 24" width="32" height="32" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">${paths[name]}</svg>`;
};
export const apps = () => `<section id="apps" class="section app-news" aria-labelledby="app-news-title">
  <div class="news-heading"><div><p class="eyebrow">06 / APP NEWS</p><h2 id="app-news-title">당신의 일상에,<br>조금 더 가까이.</h2></div><p>ONARIA의 새로운 소식.<br>지금 만날 수 있는 경험과 다음 걸음을 안내합니다.</p></div>
  <div class="web-launch">
    <div class="launch-copy"><span class="release-badge"><span aria-hidden="true"></span>WEB · 지금 이용 가능</span><h3>설치 없이 시작하는<br>나를 위한 잠깐의 시간.</h3><p>브라우저에서 마음을 고르고, 대화를 나누고,<br>오늘의 발견을 마음 카드에 담아보세요.</p>${button('/webapp/', 'ONARIA 웹앱 열기')}<p class="launch-footnote">모바일과 PC 브라우저에서 이용할 수 있어요.</p></div>
    <div class="launch-art" aria-label="감정 선택부터 마음 카드까지의 서비스 흐름 예시"><div class="preview-window"><div class="preview-toolbar"><span aria-hidden="true">● ● ●</span><span>ONARIA / A MOMENT FOR YOU</span></div><div class="preview-body"><img src="/assets/onaria-emblem.svg" width="52" height="52" alt="" loading="lazy"><p class="preview-question">지금, 어떤 마음인가요?</p><div class="emotion-chips" aria-hidden="true"><span>평온해요</span><span>복잡해요</span><span>감사해요</span></div><div class="preview-card"><span class="eyebrow">MY MIND CARD</span><p>마음이 머문 자리를<br>한 장에 담다.</p><div class="preview-rule" aria-hidden="true"></div><span>나의 감정 · 마음대화 · 작은 실천</span></div></div></div><p class="preview-caption">서비스 흐름을 표현한 이미지입니다.</p></div>
  </div>
  <div class="platform-grid">
    <article class="platform-card" data-platform="android"><div class="platform-top"><span class="platform-symbol android-symbol">${platformIcon('android')}</span><span class="platform-state">내부 테스트 중</span></div><h3>Android</h3><p>Google Play 내부 테스트로<br>앱의 경험을 다듬고 있습니다.</p><div class="platform-bottom">초대받은 계정으로 테스트 참여</div></article>
    <article class="platform-card" data-platform="ios"><div class="platform-top"><span class="platform-symbol">${platformIcon('ios')}</span><span class="platform-state">테스트 중</span></div><h3>iOS</h3><p>iPhone에서의 사용 경험을<br>확인하며 공개를 준비합니다.</p><div class="platform-bottom">App Store 공개 시 별도 안내</div></article>
    <article class="platform-card web-platform" data-platform="web"><div class="platform-top"><span class="platform-symbol">${platformIcon('web')}</span><span class="platform-state available">이용 가능</span></div><h3>Web</h3><p>별도 설치 없이, 익숙한 브라우저에서<br>ONARIA를 만나보세요.</p><a class="platform-bottom" href="/webapp/">웹에서 시작하기 <span aria-hidden="true">↗</span></a></article>
  </div>
  <details class="home-screen-guide"><summary>홈 화면에 추가해서 더 편하게 만나세요 <span aria-hidden="true">+</span></summary><div class="guide-columns"><p><strong>iPhone · Safari</strong>웹앱을 연 뒤 공유 메뉴에서 ‘홈 화면에 추가’를 선택하세요.</p><p><strong>Android · Chrome</strong>웹앱을 연 뒤 브라우저 메뉴에서 ‘홈 화면에 추가’ 또는 ‘앱 설치’를 선택하세요. 메뉴 이름은 브라우저에 따라 다를 수 있습니다.</p></div></details>
  <p class="news-note">현재 마음대화는 준비된 응답으로 제공됩니다. 웹의 마음 카드는 사용 중인 브라우저에 저장되며, 앱이나 다른 기기와 자동으로 동기화되지 않습니다. 브라우저 데이터를 삭제하면 저장한 기록도 지워질 수 있습니다.</p>
</section>`;
export const safety = () => `<section id="safety" class="section trust-section">${sectionTitle('07 / SAFETY & TRUST', '기술보다 먼저,<br>사람을 생각합니다.', '빠른 답변보다 지켜야 할 원칙이 있습니다.')}<div class="trust-grid">${[
  ['Safety First', '위험한 순간에는 현실의 도움부터', '위기 신호가 있는 경우 안전 안내를 우선합니다. AI 응답을 기다리기보다 현실의 긴급 지원이 필요한 순간이 있습니다.'],
  ['Privacy by Design', '필요한 정보만, 신중하게', '대화 맥락과 사용량은 목적에 맞게 처리합니다. 데이터 처리 범위와 출시 전 확정할 사항을 공개합니다.'],
  ['Source Integrity', '출처가 없으면, 단정하지 않기', '경전과 종교 자료의 맥락을 존중합니다. 충분한 근거가 없는 내용을 권위 있는 인용처럼 제시하지 않습니다.'],
  ['Human-centered AI', '교회와 전문가를 대신하지 않는 AI', 'AI는 목회자·교회 공동체·의료인·심리치료사를 대신하지 않습니다. 마음을 돌아보고 말씀과 공동체, 필요한 경우 전문적인 도움으로 다시 연결되는 첫 디지털 접점을 지향합니다.'],
].map(([en, ko, text]) => `<article><p class="eyebrow" lang="en">${en}</p><h3>${ko}</h3><p>${text}</p></article>`).join('')}</div></section>`;
export const privacy = () => `<section id="privacy" class="section split privacy-section">${sectionTitle('08 / PRIVACY', '개인적인 이야기에는<br>분명한 설명이 필요하니까.', '무엇이 기기에 남고, 무엇이 서버로 전달되는지 알 수 있어야 합니다.')}<div class="prose"><p>마음 카드 등 일부 기록은 기기에 보관됩니다. AI 응답에는 입력한 내용과 필요한 대화 맥락이 서버로 전달되며, 설정에 따라 외부 AI 제공자가 처리할 수 있습니다.</p><p>이 홈페이지에는 광고 추적 도구나 개인정보 수집 폼을 두지 않았습니다. 정식 공개 전 확정해야 할 운영 정보도 안내합니다.</p><a class="text-link" href="/privacy">개인정보 처리 안내 읽기 <span aria-hidden="true">→</span></a></div></section>`;
export const ecosystem = () => `<section id="ecosystem" class="section ecosystem">${sectionTitle('09 / THE ONARIA ECOSYSTEM', '하나의 철학,<br>서로 다른 경험으로.', '마음을 이해하고, 각자의 가치를 존중하는 ONARIA의 방향 아래 서비스 확장을 구상합니다.')}<div class="ecosystem-root"><img src="/assets/onaria-emblem.svg" alt="" width="56" height="56" loading="lazy"><span>ONARIA</span><p>EVERY HEART HAS ITS OWN WAY</p></div><ul class="ecosystem-list">${['ONARIA', 'Catholic', 'Buddhist', 'Jewish', 'Islamic', 'Hindu', 'Confucian'].map((name, i) => `<li><span lang="en">${name}</span><span class="status">${i === 0 ? '개발·테스트 중' : '확장 구상 · 미출시'}</span></li>`).join('')}</ul><p class="note">향후 방향을 나타낸 구조입니다. 서비스명과 출시 일정은 확정되지 않았습니다.</p></section>`;
export const cta = () => `<section class="cta"><img src="/assets/onaria-emblem.svg" width="64" height="64" loading="lazy" alt=""><p class="eyebrow">10 / YOUR WAY, AT YOUR PACE</p><h2>당신의 길은,<br>지금의 마음에서 시작됩니다.</h2>${button('/services', 'ONARIA의 경험 더 알아보기')}</section>`;
export const home = () => `<section class="hero"><div class="hero-copy"><p class="wordmark">ONARIA</p><h1>모든 마음에는<br>저마다의 길이 있습니다.</h1><p class="hero-english" lang="en">EVERY HEART HAS ITS OWN WAY</p><p class="hero-description">AI와의 안전한 마음대화로 지금의 감정을 돌아보고,<br>현재의 상황과 연결되는 성경 말씀과 작은 실천을 만나는 곳.</p><div class="hero-actions">${button('/webapp/', 'ONARIA 웹앱 열기')}${button('/#apps', '앱 소식 살펴보기', true)}</div><p class="hero-note">Web 이용 가능 · Android 내부 테스트 · iOS 공개 준비 중</p></div><div class="hero-art"><div class="light-orbit" aria-hidden="true"></div><img src="/assets/onaria-emblem.svg" width="460" height="460" fetchpriority="high" alt="하나의 내면의 빛과 동등한 일곱 길을 담은 ONARIA 심볼"><p class="orbit-label" lang="en">ONE INNER LIGHT. MANY WAYS TO GROW.</p></div><a class="scroll-cue" href="#why">우리의 이야기를 만나보세요 <span aria-hidden="true">↓</span></a></section>${about()}${flow()}${services()}${apps()}${safety()}${privacy()}${cta()}`;
