import { Router, static as serveStatic } from 'express';
import { fileURLToPath } from 'node:url';

import { home, about, services, seven, safety, apps, cta, flow, ecosystem } from './website_content.js';

const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const pages = {
  '/': { title: 'ONARIA | 모든 마음에는 저마다의 길이 있습니다', description: '현재의 감정과 상황을 안전한 AI 마음대화로 돌아보고, 성경 말씀과 작은 실천으로 연결하는 신앙 기반 마음관리 서비스 ONARIA.', body: home },
  '/about': { title: 'ONARIA 소개', description: '서로 다른 마음과 길을 존중하는 ONARIA의 방향.', body: () => `${pageHero('ABOUT ONARIA', '나를 이해하는 시간,<br>서로를 존중하는 마음.', '다름을 하나의 답으로 바꾸려 하지 않습니다.')}${about()}<section class="section"><div class="cards"><article><h2>경청</h2><p>마음을 서둘러 해석하거나 단정하지 않는 대화를 지향합니다.</p></article><article><h2>다양성</h2><p>신앙과 삶의 배경이 서로 다를 수 있음을 존중합니다.</p></article><article><h2>작은 실천</h2><p>오늘 할 수 있는 작은 행동과 성찰에 집중합니다.</p></article></div></section>${cta()}` },
  '/services': { title: 'ONARIA 서비스', description: '감정 체크인, 안전한 AI 마음대화, 성경 말씀 연결, 작은 실천과 기록. ONARIA의 현재 구현 범위와 Closed Beta 준비 상태를 안내합니다.', body: () => `${pageHero('THE ONARIA EXPERIENCE', '마음을 말하고,<br>나를 돌아보는 경험.', '현재 모바일 앱을 테스트하며 흐름을 다듬고 있습니다.')}${flow()}${services()}${apps()}${safety()}${ecosystem()}` },
  '/traditions': { title: '일곱 전통 | ONARIA', description: '개신교, 가톨릭, 불교, 유대교, 이슬람, 힌두교, 유교. 동등한 존중과 출처에 대한 책임.', body: () => `${pageHero('SEVEN PATHS', '길은 달라도,<br>존중은 같습니다.', '전통을 섞어 하나의 교리로 제시하지 않습니다.')}${seven()}<section class="section prose"><h2>맥락과 출처를 지키는 원칙</h2><p>검색 가능한 자료와 검토된 근거를 바탕으로 성찰을 돕는 방향을 지향합니다. 이 페이지에서는 새로운 경전 인용이나 교리 해석을 제공하지 않습니다.</p><p>AI의 설명은 해당 종교 기관이나 전문가의 공식 입장을 대변하지 않습니다.</p></section>` },
  '/privacy': { title: '개인정보 처리 안내 | ONARIA', description: 'ONARIA의 수집 항목, 처리 목적과 데이터 관리 방법을 안내합니다.', body: () => legal('개인정보 처리 안내', `<p class="notice">운영자: 조세진 · 개인정보 보호 및 고객지원: <a href="mailto:vjsjv7003@gmail.com">vjsjv7003@gmail.com</a>. 이 안내는 앱의 데이터 처리와 이용자의 관리 방법을 설명합니다.</p><h2>수집 항목과 목적</h2><p>소셜 로그인 시 로그인 제공자와 계정 식별자를 회원 인증·계정 연결에 사용합니다. 이름, 휴대폰 번호, 교회명은 선택 입력이며 입력한 경우 회원정보에 저장합니다. 마음대화에는 사용자가 선택한 감정·강도, 입력 문장과 전달한 최근 대화 맥락이 응답 생성을 위해 서버로 전송됩니다. 종교·건강 등 민감한 내용과 타인의 개인정보를 불필요하게 입력하지 마세요.</p><h2>기기 저장과 음성</h2><p>저장한 마음카드, 말씀, 여정과 임시 문장은 기기에 보관됩니다. 앱의 개인정보와 기록 관리에서 각각 삭제할 수 있습니다. 기기 백업에 포함되는 자료는 이용 중인 운영체제·백업 설정에 따라 별도로 관리해야 합니다. 음성 입력은 기기의 음성인식 기능을 이용해 텍스트로 변환되며 플랫폼 제공자가 처리할 수 있습니다. ONARIA 서버에 음성 파일을 보관하는 기능은 없습니다. 음성 권한을 거부하고 텍스트로 사용할 수 있습니다.</p><h2>외부 AI 처리</h2><p>외부 AI 응답 기능은 전달 대상과 항목을 확인한 이용자의 허용에 따라 사용합니다. 운영 설정에서 외부 AI가 꺼져 있으면 외부 AI로 전달하지 않습니다. AI 제공자가 처리하는 국가·보유조건 등은 실제 서비스 설정과 일치하는 고지·동의가 준비된 뒤 사용해야 합니다. ONARIA는 전문적인 진단이나 치료를 제공하지 않습니다.</p><h2>보유와 삭제</h2><p>회원정보는 계정 유지에 사용되며 앱에서 본인 인증 후 회원탈퇴하면 활성 회원 DB의 회원정보와 연결된 로그인 식별자를 삭제합니다. 보안용 세션·AI 사용량 등 서비스 운영 기록과 별도 백업은 회원 DB와 별개입니다. 현재 전체 데이터에 대한 1년 자동 파기를 제공한다고 약속하지 않습니다. 백업·운영 로그의 확정된 보유기간과 삭제 절차는 정식 서비스 제출 전에 운영 환경과 대조해야 합니다. 기기에 저장한 기록은 계정 삭제와 별도로 앱의 기록 삭제 기능에서 관리하세요.</p><h2>운영 기록과 쿠키</h2><p>AI 사용량에는 토큰 수·비용 추정치·가명화 식별자가 포함될 수 있습니다. 안전 운영 화면에는 위험 수준·분류·시간과 집계를 표시하며 대화 원문을 기본 표시하지 않습니다. 공개 홈페이지에는 광고 추적 도구가 없습니다. 관리자 로그인에는 최대 30분 유효한 필수 세션 쿠키를 사용합니다. 관리자 API 응답은 오프라인 캐시에 저장하지 않습니다.</p><h2>권리 행사와 문의</h2><p>열람·정정·삭제 또는 서비스 문의는 <a href="mailto:vjsjv7003@gmail.com">vjsjv7003@gmail.com</a>으로 요청할 수 있습니다. 이메일에 비밀번호·로그인 토큰·주민등록번호를 보내지 마세요. 요청한 계정의 소유 확인 후 안내합니다. 앱을 사용할 수 없는 경우에도 같은 주소로 삭제 절차를 문의할 수 있습니다. 이메일만으로 인증을 우회하거나 타인의 계정을 삭제하지 않습니다.</p>`) },
  '/account-deletion': { title: '계정 및 데이터 삭제 | ONARIA', description: 'ONARIA 계정과 기기 기록의 삭제 방법을 안내합니다.', body: () => legal('계정 및 데이터 삭제', `<p class="notice">회원탈퇴는 로그인한 본인 계정에서 처리합니다. 계정 소유 확인 없이 전화번호나 회원번호만으로 삭제하지 않습니다.</p><h2>앱에서 삭제</h2><p>홈 메뉴의 계정 관리에서 회원탈퇴를 선택하고 삭제 안내를 확인하세요. Apple 계정이 연결된 경우 Apple 본인 확인이 필요합니다. 인증 또는 삭제에 실패하면 완료로 표시하지 않으며 다시 시도할 수 있습니다.</p><h2>삭제되는 정보</h2><p>활성 회원 DB의 회원정보와 연결된 소셜 로그인 식별자를 삭제합니다. 기기에만 저장된 마음카드·말씀·여정·임시 문장은 개인정보와 기록 관리의 개별 삭제 기능으로 별도 삭제할 수 있습니다. 계정 삭제를 기기 백업이나 운영 기록의 물리적 완전 삭제로 해석하지 마세요.</p><h2>앱을 사용할 수 없는 경우</h2><p><a href="mailto:vjsjv7003@gmail.com">vjsjv7003@gmail.com</a>으로 계정 삭제 절차를 문의하세요. 비밀번호·로그인 토큰·주민등록번호는 보내지 마세요. 담당자가 안전한 계정 소유 확인 절차를 안내합니다. 별도의 익명 웹 삭제 폼은 제공하지 않습니다.</p><h2>보유기간과 별도 기록</h2><p>회원 DB 외의 운영 로그·백업·가명 사용량 기록에 적용되는 보유·파기 절차는 개인정보 처리 안내를 확인하세요. 출시 전에 실제 운영 환경의 기간과 파기 방식에 대한 최종 확인이 필요합니다.</p>`) },
  '/terms': { title: '이용 안내 | ONARIA', description: 'ONARIA의 서비스 범위와 이용자의 선택·문의 방법을 안내합니다.', body: () => legal('이용 안내', `<p class="notice">운영자: 조세진 · 고객지원: <a href="mailto:vjsjv7003@gmail.com">vjsjv7003@gmail.com</a>.</p><h2>서비스 범위</h2><p>ONARIA는 감정 표현, 자기 성찰, 성경 말씀과 작은 실천을 연결하는 서비스입니다. 의료적 진단·치료, 전문 상담 또는 종교 기관의 공식 자문을 제공하지 않습니다. 제공 기능과 지원 플랫폼은 앱의 실제 안내를 따릅니다.</p><h2>이용 대상</h2><p>첫 출시 서비스는 만 18세 이상 성인을 대상으로 합니다. 만 18세 미만은 가입·이용할 수 없습니다. 앱 가입 시 성인 여부를 확인합니다.</p><h2>이용 요금</h2><p>현재 ONARIA는 무료로 제공하며 앱 내 구매·유료 구독·결제 기능은 제공하지 않습니다. 향후 유료 기능을 도입한다면 이용 조건과 스토어 결제 정책을 사전에 안내합니다.</p><h2>계정과 이용자의 선택</h2><p>본인의 소셜 계정으로 로그인하세요. 이름·전화번호·교회명은 선택 입력입니다. 외부 AI 처리를 허용하지 않거나 음성 권한을 거부할 수 있습니다. 개인정보와 기록 관리에서 기기 기록 삭제 및 본인 인증 후 회원탈퇴를 요청할 수 있습니다.</p><h2>응답과 콘텐츠의 한계</h2><p>AI 응답에는 오류가 있을 수 있습니다. 중요한 결정은 신뢰할 수 있는 전문가와 확인해 주세요. 긴급한 위험이 있는 경우 앱의 답변을 기다리기보다 현실의 긴급 지원을 우선해 주세요. 성경 인용은 표시된 출처와 번역을 확인하세요. AI의 설명은 종교 기관의 공식 입장을 대변하지 않습니다.</p><h2>이용 시 배려</h2><p>타인의 개인정보나 공개 권한이 없는 민감한 자료를 입력하지 마세요. 타인 사칭, 서비스 방해, 안전 장치 우회 및 타인의 권리를 침해하는 이용을 삼가 주세요.</p><h2>변경·중단과 문의</h2><p>점검이나 장애로 이용이 제한될 수 있습니다. 서비스의 중요한 이용 조건이 변경되는 경우 앱 또는 홈페이지를 통해 알립니다. 불편·삭제·권리 관련 문의는 고객지원 이메일로 요청할 수 있습니다. 적용 법률·분쟁 절차는 확정된 운영 조건을 검토한 후 정식 이용약관에 반영해야 합니다.</p>`) },
};
function pageHero(tag, title, text) { return `<section class="page-hero"><p class="eyebrow">${tag}</p><h1>${title}</h1><p>${text}</p></section>`; }
function legal(title, body) { return `${pageHero('SERVICE INFORMATION', title, '데이터 처리·서비스 이용 안내 · 2026-10-07')}<article class="section legal prose">${body}</article>`; }

export function websiteRouter({ publicOrigin }) {
  const router = Router();
  const parsed = new URL(publicOrigin);
  if (!['https:', 'http:'].includes(parsed.protocol) || parsed.username || parsed.password) throw new Error('Invalid PUBLIC_ORIGIN');
  const origin = parsed.origin;
  router.use('/assets', serveStatic(fileURLToPath(new URL('../public/website', import.meta.url)), { maxAge: '1h', dotfiles: 'deny' }));
  router.get('/robots.txt', (_req, res) => res.type('text').send(`User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /v1/\nSitemap: ${origin}/sitemap.xml\n`));
  router.get('/sitemap.xml', (_req, res) => res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${Object.keys(pages).map(path => `<url><loc>${escape(origin + path)}</loc></url>`).join('')}</urlset>`));
  for (const [path, page] of Object.entries(pages)) router.get(path, (_req, res) => {
    const canonical = escape(origin + path);
    res.set('Cache-Control', 'public, max-age=60');
    res.type('html').send(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(page.title)}</title><meta name="description" content="${escape(page.description)}"><meta name="robots" content="index,follow"><meta name="theme-color" content="#faf8f3"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:locale" content="ko_KR"><meta property="og:site_name" content="ONARIA"><meta property="og:title" content="${escape(page.title)}"><meta property="og:description" content="${escape(page.description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${escape(origin)}/assets/social-preview.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${escape(page.title)}"><meta name="twitter:description" content="${escape(page.description)}"><meta name="twitter:image" content="${escape(origin)}/assets/social-preview.png"><meta property="og:image:alt" content="ONARIA ? EVERY HEART HAS ITS OWN WAY"><script type="application/ld+json">${JSON.stringify({ "@context": "https://schema.org", "@type": "Organization", name: "ONARIA", url: origin, logo: origin + "/assets/onaria-emblem.svg", slogan: "EVERY HEART HAS ITS OWN WAY" }).replace(/</g, "\\u003c")}</script><link rel="icon" href="/assets/onaria-emblem.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css"><script src="/assets/site.js" defer></script></head><body><a class="skip-link" href="#main">본문 바로가기</a><header class="site-header"><a class="brand" href="/" aria-label="ONARIA 홈"><img src="/assets/onaria-emblem.svg" width="42" height="42" alt=""><span>ONARIA</span></a><button class="menu-button" type="button" aria-expanded="false" aria-controls="site-nav">메뉴 <span aria-hidden="true">☰</span></button><nav id="site-nav" aria-label="주 메뉴"><a href="/about"${path === '/about' ? ' aria-current="page"' : ''}>ONARIA 소개</a><a href="/services"${path === '/services' ? ' aria-current="page"' : ''}>서비스</a><a class="nav-cta" href="/#apps">앱 소식 <span aria-hidden="true">↗</span></a></nav></header><main id="main" tabindex="-1">${page.body()}</main><footer class="site-footer"><div><a class="brand" href="/">ONARIA</a><p>모든 마음에는 저마다의 길이 있습니다.</p><small>EVERY HEART HAS ITS OWN WAY</small></div><nav aria-label="하단 메뉴"><a href="/about">소개</a><a href="/services">서비스</a><a href="/privacy">개인정보 처리 안내</a><a href="/terms">이용 안내</a><a href="/account-deletion">계정 및 데이터 삭제</a><a href="mailto:vjsjv7003@gmail.com">고객지원</a></nav><p class="copyright">© ONARIA · 마음의 속도를 존중합니다.</p></footer></body></html>`);
  });
  return router;
}
